# https://taskfile.dev

version: '3'

vars:
  GREETING: Hello, World!

tasks:
  default:
    cmds:
      - echo "Available tasks:"
      - echo "- download-dictionaries"
    silent: true

  download-dictionaries:
    cmds:
      - curl https://kaikki.org/eswiktionary/Espa%C3%B1ol/words/kaikki.org-dictionary-Espa%C3%B1ol-words.jsonl > /tmp/kaikki-spanish.jsonl
      - mv /tmp/kaikki-spanish.jsonl dictionaries/kaikki-spanish.jsonl
    silent: true

