# https://taskfile.dev

version: "3"

vars:
  GREETING: Hello, World!

tasks:
  default:
    cmds:
      - echo "Available tasks:"
      - echo "- download-dictionaries"
      - echo "- build"
      - echo "- test"
      - echo "- clean-tests"
    silent: true

  download-dictionaries:
    cmds:
      - curl https://kaikki.org/eswiktionary/Espa%C3%B1ol/words/kaikki.org-dictionary-Espa%C3%B1ol-words.jsonl > /tmp/kaikki-spanish.jsonl
      - mv /tmp/kaikki-spanish.jsonl dictionaries/kaikki-spanish.jsonl
    silent: true

  build:
    cmds:
      - go build -o bin/lexir ./cmd/lexir/main.go
    silent: true

  test:
    cmds:
      - go test ./...
      - go vet ./...
      - golangci-lint run
    silent: true

  clean-tests:
    cmds:
      - go clean -testcache
    silent: true
